# Generated by Django 4.0.3 on 2022-04-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province_State', models.CharField(max_length=100)),
                ('Last_Update', models.CharField(max_length=100)),
                ('Lat', models.CharField(max_length=100)),
                ('Long', models.CharField(max_length=100)),
                ('Confirmed', models.CharField(max_length=100)),
                ('Deaths', models.CharField(max_length=100)),
                ('Case_Fatality_Ration', models.CharField(max_length=100)),
            ],
        ),
    ]
